GET http://localhost:3001/api/persons/1

###

GET http://localhost:3001/api/persons HTTP/1.1

###

GET http://localhost:3001/api/persons/8 HTTP/1.1

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "Test",
    "number": "1231231313"
}

###

DELETE https://arcane-ocean-07813.herokuapp.com/api/persons/1 HTTP/1.1
